### PR TITLE
Restyle web editor loader

### LINKED ISSUE #252: Absent demo project link in web editor
### Tested versions

Web editor

### System information

Web editor

### Issue description

https://github.com/blazium-engine/blazium.app/issues/22

### Steps to reproduce

https://editor-nightly.blazium.app/demo.zip

### Minimal reproduction project (MRP)

web editor

### PR DESCRIPTION
**Pull request by sshiiden**
# New look
image

I will probably return to it after release, for now this is better than having the normal godot style.
Closes #252

### CODE REVIEW

File: misc/dist/html/service-worker.js [hunk 1]
```diff
@@ -129,8 +127,7 @@ self.addEventListener(
 					return cached;
 				}
 				// Try network if don't have it in cache.
-				const response = await fetchAndCache(event, cache, isCachable);
-				return response;
+				return fetchAndCache(event, cache, isCacheable);
```
Comment (Ughuuu) [inline misc/dist/html/service-worker.js:130]: previously it was awaiting this, now it wont await it anymore.

File: misc/dist/html/service-worker.js [hunk 2]
```diff
@@ -112,8 +111,7 @@ self.addEventListener(
 					if (missing) {
 						try {
 							// Try network if some cached file is missing (so we can display offline page in case).
-							const response = await fetchAndCache(event, cache, isCachable);
-							return response;
+							return fetchAndCache(event, cache, isCacheable);
```
Comment (Ughuuu) [inline misc/dist/html/service-worker.js:114]: same here, it wont await.

**Review by Ughuuu — DISMISSED** [review]

File: misc/dist/html/service-worker.js (hunk 2 above)
Comment (sshiiden) [reply misc/dist/html/service-worker.js]: forgot to readd it

**Review by Ughuuu — APPROVED** [review]
